resolver: ghc-9.0.1
packages:
  - .
extra-deps:
  - hakyll-4.14.1.0
  - aeson-1.5.6.0
  - blaze-html-0.9.1.2
  - blaze-markup-0.8.2.8
  - data-default-0.7.1.1
  - file-embed-0.0.15.0
  - fsnotify-0.3.0.1
  - hashable-1.3.3.0
  - http-conduit-2.3.8
  - http-types-0.12.3
  - lifted-async-0.10.2.1
  - lrucache-1.2.0.1
  - network-uri-2.6.4.1
  - optparse-applicative-0.16.1.0
  - pandoc-2.14.2
  - random-1.2.0
  - regex-tdfa-1.3.1.1
  - req-3.8.0
  - resourcet-1.2.4.3
  - scientific-0.3.7.0
  - tagsoup-0.14.8
  - time-locale-compat-0.1.1.5
  - unordered-containers-0.2.14.0
  - vector-0.12.3.0
  - wai-3.2.3
  - wai-app-static-3.1.7.2
  - warp-3.3.17
  - yaml-0.11.5.0
