name: Update Blog
on: [push]
jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10'
          cabal-version: '3.4'
      - name: Build the hakyll program
        run: cabal build --ghc-option=-O0
      - name: Build the site
        run: cabal run site -O2 -- build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
